language: go
go:
  - "1.10.x"

addons:
  apt:
    update: true
    packages:
    # needed for the nfpm pipe:
    - rpm
    sources:
    - sourceline: deb https://dl.bintray.com/go-swagger/goswagger-debian ubuntu main

# needed for the docker pipe
services:
- docker

before_install:
- sudo apt-get install swagger --allow-unauthenticated -y
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
- dep ensure

jobs:
  include:
    - stage: test
      script: make test-coverage
    - stage: build
      script: make build
      after_success:
      # docker login is required if you want to push docker images.
      # DOCKER_PASSWORD should be a secret in your .travis.yml configuration.
      - test -n "$TRAVIS_TAG" && docker login -u=myuser -p="$DOCKER_PASSWORD"

      # calls goreleaser
      deploy:
      - provider: script
        skip_cleanup: true
        script: curl -sL https://git.io/goreleaser | bash
        on:
          tags: true
          condition: $TRAVIS_OS_NAME = linux
