# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "github.com/Flaque/filet"

[[constraint]]
  branch = "master"
  name = "github.com/gammazero/workerpool"

[[constraint]]
  branch = "master"
  name = "github.com/getlunaform/go-terraform"

[[constraint]]
  name = "github.com/go-openapi/errors"
  version = "0.15.0"

[[constraint]]
  name = "github.com/go-openapi/loads"
  version = "0.15.0"

[[constraint]]
  name = "github.com/go-openapi/runtime"
  version = "0.15.0"

[[constraint]]
  name = "github.com/go-openapi/spec"
  version = "0.15.0"

[[constraint]]
  name = "github.com/go-openapi/strfmt"
  version = "0.15.0"

[[constraint]]
  name = "github.com/go-openapi/swag"
  version = "0.15.0"

[[constraint]]
  name = "github.com/go-openapi/validate"
  version = "0.15.0"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.13.2"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/jwalterweatherman"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/teris-io/shortid"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sys"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[prune]
  go-tests = true
  unused-packages = true
